Make configuration compliant with latest symfony versions
adrenalinkin/swagger-resolver-bundle pull request #20
Opened 2020-03-19 13:10 UTC by msphn

This change is probably breaking.
I could need your help to check if it's still working with 3.4 and 4!

2020-03-19 21:06 UTC, adrenalinkin requested changes

2020-03-19 21:06 UTC, adrenalinkin commented on DependencyInjection/Configuration.php
> +        $rootNode = $treeBuilder->getRootNode();
Please use this construct
```php
        if (method_exists($treeBuilder, 'getRootNode')) {
            $rootNode = $treeBuilder->getRootNode();
        } else {
            // BC layer for symfony/config 4.1 and older
            $rootNode = $treeBuilder->root('linkin_swagger_resolver');
        }
```
And do not forget import `method_exists` into `use` section

2020-03-20 08:32 UTC, msphn commented
For me works fine now. :-)

2020-03-20 16:13 UTC, merged

2020-03-20 16:14 UTC, adrenalinkin commented
@msphn Good job.
I plan add tests and release first major version. So keep in touch.

2020-03-20 18:10 UTC, msphn commented
I can help you out, I set up CI before. You want to set up travis?

2020-03-21 17:14 UTC, adrenalinkin commented
@msphn yes you can :)
But keep in mind - currently I have a lot of work on my job and can answer to you with delay